from __future__ import annotations

from typing import Protocol

from risk_dashboard.modules.community.domain.entities import (
    CommunityChallengeProgress,
    CommunityComment,
    CommunityMembership,
    CommunityModerationEvent,
    CommunityNotificationState,
    CommunityPost,
)


class CommunityMembershipRepository(Protocol):
    def list_memberships(self, *, user_id: str) -> list[CommunityMembership]: ...

    def get_membership(self, *, user_id: str, space_id: str) -> CommunityMembership | None: ...

    def save_membership(self, membership: CommunityMembership) -> CommunityMembership: ...


class CommunityPostRepository(Protocol):
    def list_posts(self, *, space_id: str, visible_only: bool = True) -> list[CommunityPost]: ...

    def get_post(self, *, post_id: str) -> CommunityPost | None: ...

    def save_post(self, post: CommunityPost) -> CommunityPost: ...

    def update_post_status(self, *, post_id: str, moderation_status: str) -> None: ...

    def count_recent_posts(self, *, user_id: str, minutes: int) -> int: ...

    def count_posts_by_status(self, *, user_id: str, status: str) -> int: ...

    def count_posts_by_status_for_space(self, *, user_id: str, space_id: str, status: str) -> int: ...


class CommunityCommentRepository(Protocol):
    def list_comments(self, *, post_id: str, visible_only: bool = True) -> list[CommunityComment]: ...

    def get_comment(self, *, comment_id: str) -> CommunityComment | None: ...

    def save_comment(self, comment: CommunityComment) -> CommunityComment: ...

    def update_comment_status(self, *, comment_id: str, moderation_status: str) -> None: ...


class CommunityModerationRepository(Protocol):
    def save_event(self, event: CommunityModerationEvent) -> CommunityModerationEvent: ...

    def list_pending_queue(self) -> list[CommunityModerationEvent]: ...


class CommunityChallengeProgressRepository(Protocol):
    def get_progress(self, *, challenge_id: str, user_id: str) -> CommunityChallengeProgress | None: ...

    def list_progress(self, *, user_id: str) -> list[CommunityChallengeProgress]: ...

    def save_progress(self, progress: CommunityChallengeProgress) -> CommunityChallengeProgress: ...


class CommunityNotificationRepository(Protocol):
    def list_notifications(self, *, user_id: str, active_only: bool = True) -> list[CommunityNotificationState]: ...

    def replace_notifications(self, *, user_id: str, notifications: list[CommunityNotificationState]) -> None: ...

    def update_status(self, *, notification_id: str, status: str) -> CommunityNotificationState | None: ...
